import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    fontFamily: { inter: ["inter"] },
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
    },
  },
  safelist: [
    "bg-sky-50",
    "bg-indigo-50",
    "bg-fuchsia-50",
    "bg-rose-50",
    "bg-orange-50",
    "bg-amber-50",
    "bg-green-50",
    "border-sky-50",
    "border-indigo-50",
    "border-fuchsia-50",
    "border-rose-50",
    "border-orange-50",
    "border-amber-50",
    "border-green-50",
    "border-sky-100",
    "border-indigo-100",
    "border-fuchsia-100",
    "border-rose-100",
    "border-orange-100",
    "border-amber-100",
    "border-green-100",
    "bg-sky-800",
    "bg-indigo-800",
    "bg-fuchsia-800",
    "bg-rose-800",
    "bg-orange-800",
    "bg-amber-800",
    "bg-green-800",
    "border-sky-800",
    "border-indigo-800",
    "border-fuchsia-800",
    "border-rose-800",
    "border-orange-800",
    "border-amber-800",
    "border-green-800",
  ],
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
